N_f = 10; N_r = 1;
generate_confidence_plot;
N_f = 2; N_r = 2;
generate_confidence_plot;
N_f = 1; N_r = 10;
generate_confidence_plot;
N_f = 10; N_r = 10;
generate_confidence_plot;
N_f = 20; N_r = 20;
generate_confidence_plot;
N_f = 50; N_r = 50;
generate_confidence_plot;
N_f = 100; N_r = 100;
generate_confidence_plot;
N_f = 300; N_r = 300;
generate_confidence_plot;
